import os
from docx import Document
from docx.shared import Pt, Inches, RGBColor
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

def add_heading(doc, text, level=1):
    h = doc.add_heading(text, level=level)
    h.style.font.color.rgb = RGBColor(16, 185, 129) # Emerald

def append_brsr_to_student_manual(file_path):
    doc = Document(file_path)
    
    doc.add_page_break()
    add_heading(doc, "Appendix: BRSR NGRBC Deep-Dive Track", level=1)
    
    p = doc.add_paragraph()
    p.add_run("The Business Responsibility and Sustainability Reporting (BRSR) Track").bold = True
    p.add_run(" is a 5-round, rigorous module designed around the Securities and Exchange Board of India (SEBI) guidelines and the National Guidelines on Responsible Business Conduct (NGRBC).")
    
    doc.add_heading("Overview & Mechanics", level=2)
    doc.add_paragraph(
        "When your facilitator enables this track, your executive team will navigate complex decision trees covering the nine NGRBC principles. "
        "Each round tests your ability to balance Essential Indicators (mandatory compliance) against Leadership Indicators (voluntary excellence)."
    )
    
    doc.add_heading("Round Structure", level=3)
    rounds = [
        "Round 1: Governance & Ethics (Principles 1 & 7) - Radical transparency vs. compliance pragmatism.",
        "Round 2: Workforce Well-being (Principles 3 & 5) - Implementing a living wage across tier-1 suppliers.",
        "Round 3: Environmental Footprint (Principles 2 & 6) - Circular procurement vs. conventional sourcing.",
        "Round 4: Value Chain Assurance (Principles 4, 8 & 9) - Addressing greenwash risks in downstream channels.",
        "Round 5: Integrated Reporting (BRSR Core) - Achieving reasonable assurance on value chain metrics."
    ]
    for r in rounds:
        doc.add_paragraph(r, style='List Bullet')
        
    doc.add_heading("Consequences & The Executive Dashboard", level=3)
    doc.add_paragraph(
        "You must monitor your BRSR standing via the 'BRSR' dashboard accessed from the Cockpit toolbar. "
        "Achieving 'BRSR Pioneer' status unlocks a highly lucrative +0.05 ESG Alpha Dividend that permanently boosts your Regenerative Multiple (M_R). "
        "However, triggering 'Governance Fragility' or 'Greenwash Risk' flags will result in dynamic crisis events, directly draining corporate treasury or crashing group reputation."
    )
    
    doc.save("Muressons_Student_Manual_v4.docx")
    print("Created Muressons_Student_Manual_v4.docx")


def append_brsr_to_facilitator_manual(file_path):
    doc = Document(file_path)
    
    doc.add_page_break()
    add_heading(doc, "Module Supplement: SEBI BRSR NGRBC Implementation", level=1)
    
    doc.add_paragraph(
        "The BRSR NGRBC side track has been integrated into the central Muressons pedagogical engine. "
        "It acts as a stringent, 5-round gauntlet focusing on Indian and global sustainability reporting standards."
    )
    
    doc.add_heading("Pedagogical Goals", level=2)
    doc.add_paragraph("By triggering this track, facilitators can evaluate students on:", style='List Bullet')
    doc.add_paragraph("Distinguishing between SEBI's 'Essential' vs. 'Leadership' indicators.", style='List Bullet')
    doc.add_paragraph("Navigating the severe consequences of 'Greenwashing' in value chain assurance.", style='List Bullet')
    doc.add_paragraph("Understanding the long-term financial Alpha generated by proactive BRSR Core assurance.", style='List Bullet')

    doc.add_heading("Facilitator Controls & Live Interventions", level=2)
    doc.add_paragraph(
        "The track feeds dynamic crises directly into the main Engine Loop. "
        "For example, if a team accumulates a 'Governance Fragility' flag in Round 1, "
        "the engine will autonomously trigger a 'Whistleblower Crisis' in Round 5, bleeding their corporate treasury. "
        "Use this as a powerful debriefing tool to illustrate the 'long-tail' risk of poor ESG governance."
    )
    
    doc.save("Muressons_Facilitator_Manual_v3.docx")
    print("Created Muressons_Facilitator_Manual_v3.docx")

if __name__ == "__main__":
    if os.path.exists("Muressons_Student_Manual_v3.docx"):
        append_brsr_to_student_manual("Muressons_Student_Manual_v3.docx")
    else:
        print("Student manual v3 not found.")
        
    if os.path.exists("Muressons_Facilitator_Manual_v2.docx"):
        append_brsr_to_facilitator_manual("Muressons_Facilitator_Manual_v2.docx")
    else:
        print("Facilitator manual v2 not found.")

