"""Patch the glossary in admin_analytics.py with expanded 42-term version."""
import re

TARGET = "backend/admin_analytics.py"

NEW_GLOSSARY = '''_glossary_terms: list = [
    # -- Financial Metrics --
    {"id": "ebitda", "term": "EBITDA", "definition": "Earnings Before Interest, Taxes, Depreciation, and Amortization. The primary operational profitability metric. At R10, EBITDA is carbon-adjusted by deducting total carbon tonnage x carbon tax ($250/tonne).", "tags": ["finance", "profitability", "earnings", "valuation"], "weblink": "https://www.investopedia.com/terms/e/ebitda.asp"},
    {"id": "csf_pool", "term": "Corporate Strategic Fund (CSF)", "definition": "The master liquidity pool: CSF = Sum(Revenue_i - OPEX_i) - Dividends. If total CAPEX exceeds 20% of treasury, a loan at 12% interest is auto-triggered. The primary resource constraint for all investment decisions.", "tags": ["finance", "investment", "treasury", "capital"], "weblink": ""},
    {"id": "treasury", "term": "Treasury", "definition": "Corporate cash reserves. Below $5M triggers Turnaround Mode (survival phase). Depleted by investments, crises, loan interest, and operating costs.", "tags": ["finance", "cash", "investment", "liquidity"], "weblink": ""},
    {"id": "terminal_value", "term": "Terminal Value (TV)", "definition": "Simulated market capitalisation at end of the 5-year cycle. TV = (Terminal_EBITDA + Green_Fund) x Exit_Multiple (12x) x Regenerative_Multiple (M_R). Represents what an ESG-informed institutional investor would pay.", "tags": ["finance", "valuation", "exit", "strategy"], "weblink": "https://www.investopedia.com/terms/t/terminalvalue.asp"},
    {"id": "capex", "term": "CAPEX (Capital Expenditure)", "definition": "One-time investment per BU per round from the CSF pool. CAPEX > 10% of BU revenue triggers a 1-round implementation lag. CAPEX > $3M has a 25% chance of +15% cost overrun.", "tags": ["finance", "investment", "capital", "expenditure"], "weblink": "https://www.investopedia.com/terms/c/capitalexpenditure.asp"},
    {"id": "opex", "term": "OPEX (Operating Expenditure)", "definition": "Ongoing BU operational costs. Reduced by the Synergy Engine (sqrt(ratio) x 0.7 x synergy_multiplier). Increased by inflation (+2.5%/round), burnout, brain-drain, and technical debt.", "tags": ["finance", "operations", "costs", "expenditure"], "weblink": "https://www.investopedia.com/terms/o/operating_expense.asp"},
    {"id": "cost_of_capital", "term": "Cost of Capital", "definition": "Investor-required rate of return. Follows macro cycles: R1-3 easing (-0.5%), R4-6 neutral, R7-9 tightening (+0.5%), R10 crisis (+1.0%). Higher rates penalise late-stage treasury recovery.", "tags": ["finance", "treasury", "investors", "interest"], "weblink": "https://www.investopedia.com/terms/c/costofcapital.asp"},
    {"id": "green_fund", "term": "Green Transition Fund (GTF)", "definition": "Ring-fenced capital reserve from early-round ESG decisions, analogous to a green bond issuance (ICMA framework). Drawn down first before corporate treasury for R7-R9 sustainable transition costs.", "tags": ["finance", "green bond", "sustainability", "investment"], "weblink": "https://www.icmagroup.org/sustainable-finance/the-principles-guidelines-and-handbooks/green-bond-principles-gbp/"},
    {"id": "dividend_ratchet", "term": "Dividend Ratchet", "definition": "Board pressure: cutting dividends by more than 20% vs. last round triggers -5 reputation. Models real-world investor expectations for distribution consistency.", "tags": ["finance", "governance", "dividends", "board"], "weblink": ""},
    # -- Sustainability & ESG --
    {"id": "esg", "term": "ESG", "definition": "Environmental, Social, and Governance. Three pillars for measuring corporate sustainability and ethical impact. First defined by the UN Principles for Responsible Investment (2006).", "tags": ["esg", "sustainability", "environment", "social", "governance"], "weblink": "https://www.unpri.org/about-us/what-are-the-principles-for-responsible-investment"},
    {"id": "ncd", "term": "Natural Capital Debt (NCD)", "definition": "BU-level environmental liability. Interest rate = Base_Rate + NCD x 0.0001, compounds each round. At NCD=5,200 the effective rate is 57%. Models planetary boundaries as financial risk.", "tags": ["environment", "liability", "sustainability", "natural capital"], "weblink": "https://naturalcapitalcoalition.org/natural-capital-protocol/"},
    {"id": "social_license", "term": "Social License to Operate (SLO)", "definition": "BU-level score [0-100] quantifying community and worker acceptance (Thomson & Boutilier, 2011). Below 75 average triggers -0.40 M_R Instability Discount. Below 50 creates R9 strike risk (75%).", "tags": ["social", "stakeholder", "community", "legitimacy"], "weblink": "https://socialicense.com/definition.html"},
    {"id": "carbon_intensity", "term": "Carbon Intensity", "definition": "BU-level metric (tCO2-e per $M revenue). Scope 3 supply chain footprint is 4x direct emissions. Carbon tonnage at R10 is taxed at $250/tonne (climate pathway: $750/tonne).", "tags": ["environment", "emissions", "carbon", "climate"], "weblink": "https://www.ghgprotocol.org/sites/default/files/standards/ghg-protocol-revised.pdf"},
    {"id": "scope3", "term": "Scope 3 Emissions", "definition": "Indirect value chain emissions (upstream suppliers, downstream customers). Typically 4x direct emissions per GHG Protocol. R3 decisions directly shape Scope 3 trajectory.", "tags": ["environment", "emissions", "supply chain", "carbon"], "weblink": "https://www.ghgprotocol.org/standards/scope-3-standard"},
    {"id": "governance_risk", "term": "Governance Risk", "definition": "Score [0-100] reflecting corporate governance quality. High values reduce cash efficiency (revenue x (1 - gov_risk/500)). Feeds supply chain contagion and R9 strike probability.", "tags": ["governance", "risk", "compliance", "board"], "weblink": "https://www.oecd.org/corporate/principles-corporate-governance/"},
    {"id": "water_dependency", "term": "Water Dependency Index", "definition": "BU-level [0-1] score for operational freshwater reliance. Modified exclusively in R8 (Blue Stress). Pharma baseline: 0.85. Maps to TCFD physical climate risk exposures.", "tags": ["environment", "water", "physical risk", "tcfd"], "weblink": "https://www.wri.org/aqueduct"},
    {"id": "burnout", "term": "Staff Burnout", "definition": "Global workforce burnout score [0-100]. HR investment reduces (-10 high, -4 medium). No investment adds +3 drift. OPEX penalty above 20. WHO ICD-11 recognised (2019).", "tags": ["social", "workforce", "hr", "talent"], "weblink": "https://www.who.int/news/item/28-05-2019-burn-out-an-occupational-phenomenon-international-classification-of-diseases"},
    {"id": "workforce_readiness", "term": "Workforce Readiness", "definition": "Global competence score [0-100, starts 50]. High HR: +8, Medium: +4, None: -5 per round. Below 40: pillar effectiveness -20%. Above 75: +0.10 M_R bonus.", "tags": ["social", "workforce", "hr", "competence", "learning"], "weblink": ""},
    {"id": "reputation", "term": "Group Reputation", "definition": "Composite [0-100] stakeholder perception score. The Contagion Engine propagates single-BU damage to the group. Below 65 triggers Talent Brain-Drain on Software BU.", "tags": ["social", "reputation", "brand", "contagion"], "weblink": ""},
    {"id": "brand_equity", "term": "Brand Equity", "definition": "Intangible asset value from brand recognition and loyalty. Operationalised via Keller's Customer-Based Brand Equity model (Journal of Marketing, 1993).", "tags": ["social", "reputation", "brand", "strategy"], "weblink": "https://doi.org/10.2307/1252054"},
    # -- Simulation Engines --
    {"id": "contagion_engine", "term": "Contagion Engine", "definition": "Sigmoid-based reputational damage propagation: Group_Rep = AVG(BU_Rep) - 50 x sigmoid((severity-30)/15). If electronics_blindspot active, R4 severity doubles (40 to 80). Models systemic risk cascades.", "tags": ["engine", "reputation", "crisis", "sigmoid", "contagion"], "weblink": ""},
    {"id": "synergy_engine", "term": "Synergy Engine", "definition": "Diminishing-returns OPEX reduction: effective_ratio = sqrt(ratio) x 0.7; New_OPEX = Old_OPEX x (1 - effective_ratio x synergy_mult). R7C Waste-to-Energy adds +0.35 to synergy multiplier.", "tags": ["engine", "synergy", "opex", "investment", "efficiency"], "weblink": ""},
    {"id": "synergy_multiplier", "term": "Synergy Multiplier", "definition": "Factor [0.5-2.0+] amplifying CAPEX effectiveness. Decays 5%/round via VRIO. R7-C boosts +0.35. At R10, synergy x 100 must exceed 80 to unlock Resist & Integrate option.", "tags": ["strategy", "synergy", "efficiency", "competitive advantage"], "weblink": ""},
    {"id": "brain_drain", "term": "Talent Brain-Drain", "definition": "OPEX inflation for Software/Telehealth BU when Group Rep < 65. Penalty = 1 + max(0, (65-Rep)/100) x 1.5 + burnout_adj. Models ESG-driven employee exodus.", "tags": ["engine", "talent", "opex", "reputation", "hr"], "weblink": ""},
    {"id": "entropy", "term": "Natural Decay (Entropy)", "definition": "BUs with zero CAPEX lose 2% reputation and 2% SLO per round. Over 5 rounds: Rep 80 decays to 72.3. Models organisational entropy.", "tags": ["engine", "decay", "neglect", "reputation", "slo"], "weblink": ""},
    {"id": "technical_debt", "term": "Technical Debt", "definition": "4% OPEX penalty for BUs with zero investment for 2+ consecutive rounds. Combined with Natural Decay and Brain-Drain, creates a spiralling neglect cascade.", "tags": ["engine", "penalty", "neglect", "opex", "debt"], "weblink": ""},
    {"id": "greenwashing_engine", "term": "Greenwashing Engine", "definition": "Detects green rhetoric without investment. If R3C chosen and avg investment ratio < 15%, ALL BUs lose 8 SLO points. Models regulatory risk from ESG misrepresentation.", "tags": ["engine", "greenwashing", "social license", "regulation"], "weblink": "https://www.esma.europa.eu/press-news/esma-news/esma-proposes-rules-use-esg-and-sustainability-terms-funds-names"},
    {"id": "strike_engine", "term": "Strike Probability Engine", "definition": "R9 stochastic event: P_Strike = Base_Risk + ((1-SLO/100) x 0.4). If avg SLO < 50: 75% strike probability. Strike zeroes ALL BU revenue for the round.", "tags": ["engine", "strike", "workforce", "social license", "stochastic"], "weblink": ""},
    {"id": "stochastic_climate", "term": "Stochastic Climate Event (R5)", "definition": "Category-4 cyclone with 75% probability. Base damage $12M. R5-A Hard Engineering: 85% reduction (2-round delay). R5-B Nature-Based: 60%. R5-C Insurance: no reduction, blocks M_R resilience bonus.", "tags": ["engine", "climate", "physical risk", "stochastic", "tcfd"], "weblink": "https://www.fsb-tcfd.org/recommendations/"},
    {"id": "implementation_lag", "term": "Implementation Lag", "definition": "Investments > 10% of BU revenue are DEFERRED 1 round. Pay NOW, benefit NEXT round. Models real-world capital project J-curve payoff profiles.", "tags": ["engine", "investment", "timing", "capex", "delay"], "weblink": ""},
    {"id": "pending_capex", "term": "Pending CAPEX Projects", "definition": "Infrastructure investments maturing over subsequent rounds. Stored with rounds_remaining counter. R5-A Hard Engineering purchases resilience in R7, not R5.", "tags": ["engine", "capex", "infrastructure", "delayed returns"], "weblink": ""},
    # -- Scoring & Archetypes --
    {"id": "mr", "term": "Regenerative Multiple (M_R)", "definition": "Risk-adjusted valuation modifier (range 0.60-2.08). Base 1.0 + bonuses: Synergy +0.30, Resilience +0.20, Truth +0.15, Community +0.18, Governance +0.10, Workforce +0.10, Wellbeing +0.05. Penalty: Instability -0.40.", "tags": ["scoring", "valuation", "sustainability", "multiplier"], "weblink": ""},
    {"id": "instability_discount", "term": "Instability Discount", "definition": "A -0.40 penalty on M_R when average SLO < 75. The single most damaging scoring penalty, equivalent to losing ~$180M in terminal value. Models activist investor impairment pricing (cf. Danone 2021).", "tags": ["scoring", "penalty", "social license", "risk"], "weblink": ""},
    {"id": "archetypes", "term": "Corporate Archetypes", "definition": "Terminal strategy profiles based on M_R: Regenerative Titan (>=1.80, cf. Orsted), De-risked Safe-Haven (>=1.20), Fragile Giant (>=0.80), Stranded Relic (<0.80, cf. post-dieselgate VW).", "tags": ["scoring", "archetype", "profile", "classification"], "weblink": ""},
    # -- Frameworks & Regulation --
    {"id": "double_materiality", "term": "Double Materiality", "definition": "EU CSRD requirement (Article 19a): assess both Financial Materiality (risks to company) and Impact Materiality (company's impact on society/environment). Doubly-material issues are mandatory first-priority.", "tags": ["governance", "csrd", "regulation", "materiality"], "weblink": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022L2464"},
    {"id": "csrd", "term": "CSRD", "definition": "Corporate Sustainability Reporting Directive. EU directive mandating double materiality assessments for ~50,000 companies from 2025. The R2 minigame operationalises CSRD through a 6-issue materiality exercise.", "tags": ["regulation", "governance", "reporting", "eu"], "weblink": "https://finance.ec.europa.eu/capital-markets-union-and-financial-markets/company-reporting-and-auditing/company-reporting/corporate-sustainability-reporting_en"},
    {"id": "tcfd", "term": "TCFD", "definition": "Task Force on Climate-related Financial Disclosures. Framework for disclosing climate risks across Governance, Strategy, Risk Management, Metrics/Targets. The R5 stochastic event models TCFD physical risk scenario analysis.", "tags": ["regulation", "climate", "disclosure", "risk"], "weblink": "https://www.fsb-tcfd.org/recommendations/"},
    {"id": "sbti", "term": "SBTi", "definition": "Science Based Targets initiative. Framework for emissions reduction aligned with Paris Agreement. R3 decisions on Scope 3 emissions map to SBTi near-term vs. long-term pathways.", "tags": ["regulation", "climate", "targets", "emissions"], "weblink": "https://sciencebasedtargets.org/"},
    {"id": "stakeholder_map", "term": "Mendelow's Stakeholder Matrix", "definition": "2x2 Power-Interest grid classifying stakeholders by influence and engagement. R1 minigame: drag 10 stakeholders. 80%+ accuracy earns reputation bonus. Mendelow, A.L. (1991).", "tags": ["strategy", "stakeholder", "governance", "framework"], "weblink": ""},
    {"id": "vrio", "term": "VRIO Framework", "definition": "Value, Rarity, Inimitability, Organisation. Strategic resource analysis per Barney (1991). Implemented as synergy decay: synergy_mult x (1-0.05) per round. Models competitive advantage erosion.", "tags": ["strategy", "competitive advantage", "resources", "rbt"], "weblink": "https://doi.org/10.1177/014920639101700108"},
    # -- Simulation Mechanics --
    {"id": "flags", "term": "Flag Dependencies", "definition": "Persistent boolean state variables encoding past decisions into future engines. Key: electronics_blindspot (R1->R4 severity doubler), ethical_ai_overhaul (R6->M_R +0.15), synergy_unlock (R7->M_R +0.30).", "tags": ["mechanics", "flags", "path dependence", "decisions"], "weblink": ""},
    {"id": "bu", "term": "Business Unit (BU)", "definition": "One of four Muressons divisions: Pharma ($18M), Electronics ($16.5M, highest carbon 72), Consumer Goods ($10.5M), Software ($8.5M). Alternative verticals: Banking, Agriculture, Oil & Gas, Retail, Tech.", "tags": ["strategy", "organization", "business unit"], "weblink": ""},
    {"id": "strategic_pillars", "term": "Strategic Pillars Paradigm", "definition": "Advanced decision paradigm (multi_toggles) where players configure choices across 5 strategic areas (Energy, Operations, Supply Chain, Offsetting, HR) instead of single A/B/C.", "tags": ["strategy", "decisions", "paradigm", "pillars"], "weblink": ""},
    {"id": "cfo_override", "term": "CFO Override", "definition": "Emergency mechanism bypassing the R2 materiality gate for non-Quadrant-1 issues. Incurs -5 Group Reputation. Models tension between financial expedience and governance compliance.", "tags": ["governance", "finance", "risk", "override"], "weblink": ""},
    {"id": "round_pacing", "term": "Round Pacing", "definition": "Facilitator-controlled timing: Free Play (players advance freely) or Facilitator-Gated (facilitator unlocks each round). Enables synchronised classroom or self-paced individual experiences.", "tags": ["system", "facilitator", "timing", "classroom"], "weblink": ""},
    {"id": "just_transition", "term": "Just Transition", "definition": "ILO/UN framework ensuring the sustainability shift does not leave workers behind. R9: Closure (strike risk) vs. Managed Transition ($12M) vs. Community Fund ($20M, +0.18 M_R). Paris Agreement Art. 4.", "tags": ["social", "workforce", "transition", "community"], "weblink": "https://www.ilo.org/global/topics/green-jobs/WCMS_432859/lang--en/index.htm"},
    {"id": "circular_economy", "term": "Circular Economy", "definition": "Economic model eliminating waste through lifecycle redesign. R7 operationalises via Industrial Symbiosis (Option C: Waste-to-Energy), boosting synergy +0.35 and earning +0.30 M_R, the highest single bonus.", "tags": ["environment", "circularity", "waste", "strategy"], "weblink": "https://ellenmacarthurfoundation.org/topics/circular-economy-introduction/overview"},
    {"id": "ai_ethics", "term": "AI Ethics & Algorithmic Bias", "definition": "R6 crisis: algorithmic bias in recruitment AI. Option B (Ethical AI Overhaul, -$8M) earns Truth Premium (+0.15 M_R). Option C (Monetise) triggers EU AI Act costs. Models the EU AI Act (2024).", "tags": ["governance", "ai", "ethics", "regulation", "bias"], "weblink": "https://artificialintelligenceact.eu/"},
    {"id": "dynamic_capabilities", "term": "Dynamic Capabilities", "definition": "Teece (1997): ability to integrate, build, and reconfigure competencies to address changing environments. Modelled via synergy multiplier and VRIO decay. Continuous reinvestment required.", "tags": ["strategy", "theory", "competitive advantage", "capabilities"], "weblink": "https://doi.org/10.1002/(SICI)1097-0266(199708)18:7<509::AID-SMJ882>3.0.CO;2-Z"},
]'''

# Read and patch
with open(TARGET, 'r', encoding='utf-8') as f:
    content = f.read()

# Find the block to replace
pattern = r'_glossary_terms: list = \[.*?\n\]'
match = re.search(pattern, content, re.DOTALL)
if match:
    content = content[:match.start()] + NEW_GLOSSARY + content[match.end():]
    with open(TARGET, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"SUCCESS: Replaced glossary ({match.start()}-{match.end()}) with 42 terms")
else:
    print("ERROR: Could not find _glossary_terms block")
