#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# ship_stakeholder.sh — automate Steps 0–2 of the stakeholder module ship:
#   0. config integrity check   (are the wave constants present?)
#   1. clear stale bytecode + run the golden oracle twice (write, then enforce)
#   2. run the tripwires (+ optional full backend suite with --full)
#
# Usage:   ./ship_stakeholder.sh [--full] [--rebaseline]
#   --full        also run the entire backend test suite (slower)
#   --rebaseline  regenerate the golden baseline on purpose (use only when a
#                 wave is intentionally turned on by default and the trace changes)
#
# Run from the repo root (or anywhere inside it). Exits non-zero if any
# must-pass step fails, so it's CI-friendly.
# ─────────────────────────────────────────────────────────────────────────────
set -uo pipefail

# ── options ──
FULL=0; REBASELINE=0
for arg in "$@"; do
  case "$arg" in
    --full) FULL=1 ;;
    --rebaseline) REBASELINE=1 ;;
    -h|--help) grep '^#' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $arg (try --help)"; exit 2 ;;
  esac
done

# ── colours (only if stdout is a terminal) ──
if [ -t 1 ]; then
  R=$'\e[31m'; G=$'\e[32m'; Y=$'\e[33m'; B=$'\e[1m'; N=$'\e[0m'
else R=""; G=""; Y=""; B=""; N=""; fi
ok(){    echo "${G}✓${N} $*"; }
warn(){  echo "${Y}!${N} $*"; }
fail(){  echo "${R}✗${N} $*"; }
head(){  echo; echo "${B}== $* ==${N}"; }

# ── locate the repo / backend dir ──
ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
if   [ -d "$ROOT/backend" ]; then BE="$ROOT/backend"
elif [ -f "$ROOT/config.py" ] && [ -d "$ROOT/tests" ]; then BE="$ROOT"   # already in backend
else fail "cannot find the backend directory (need backend/config.py). Run from the repo."; exit 2; fi
ok "backend dir: $BE"

PY="$(command -v python3 || command -v python)"
if [ -z "$PY" ]; then fail "python not found on PATH"; exit 2; fi
if ! "$PY" -m pytest --version >/dev/null 2>&1; then
  fail "pytest not available for $PY. Install deps: pip install -r $BE/requirements.txt pytest"; exit 2
fi

STEP_FAIL=0

# ── STEP 0: config integrity ──
head "Step 0 — config integrity"
CFG="$BE/config.py"
NEEDED=(TRUST_GAIN_RATE STAKEHOLDER_SLO_COUPLING ENGAGE_TOWNHALL_COST COALITION_STRIKE_GAIN THRESHOLD_JITTER NPC_SENTIMENT_BRIDGE_WEIGHT PROMISE_KEPT_TRUST_BONUS PATIENCE_LIMIT)
MISSING=()
for k in "${NEEDED[@]}"; do grep -q "^${k}[: ]" "$CFG" || MISSING+=("$k"); done
if [ ${#MISSING[@]} -eq 0 ]; then
  ok "all ${#NEEDED[@]} stakeholder wave constants present in config.py"
else
  fail "config.py is MISSING ${#MISSING[@]} constant(s): ${MISSING[*]}"
  warn "the waves will silently no-op until these are restored (see STAKEHOLDER_SHIP_CHECKLIST.md)"
  STEP_FAIL=1
fi
# heads-up if config.py looks generated
if grep -rslE "open\(.*config\.py.*['\"]w" "$BE"/*.py "$ROOT"/scripts/*.py 2>/dev/null | grep -q .; then
  warn "config.py may be generated by a script — add constants to the generator, not just the file"
fi

# ── STEP 1: clear bytecode + golden oracle ──
head "Step 1 — clear bytecode + golden oracle"
find "$BE" -name '*.pyc' -delete 2>/dev/null
find "$BE" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null
ok "cleared stale .pyc / __pycache__"

GOLDEN="$BE/tests/golden/stakeholder_slo_trace.json"
cd "$BE"

if [ "$REBASELINE" -eq 1 ]; then
  warn "rebaseline requested — regenerating the golden baseline"
  MURESSONS_REBASELINE_GOLDEN=1 "$PY" -m pytest tests/test_stakeholder_golden_trace.py -q || { fail "rebaseline run errored"; STEP_FAIL=1; }
fi

if [ ! -f "$GOLDEN" ]; then
  echo "  no baseline yet → first run will write it"
  "$PY" -m pytest tests/test_stakeholder_golden_trace.py -q
  if [ -f "$GOLDEN" ]; then ok "golden baseline written: tests/golden/stakeholder_slo_trace.json (review + commit it)"
  else fail "golden baseline was not written — check the run above"; STEP_FAIL=1; fi
else
  ok "existing golden baseline found"
fi

echo "  enforcing run (must pass, no skips):"
if "$PY" -m pytest tests/test_stakeholder_golden_trace.py -q; then
  ok "stakeholder suite green (golden enforced + all wave unit tests pass)"
else
  fail "stakeholder suite FAILED — inspect the assertion messages above"
  STEP_FAIL=1
fi

# ── STEP 2: tripwires (+ optional full suite) ──
head "Step 2 — tripwires"
TRIP=(tests/test_role_hierarchy_sync.py tests/test_qa_monte_carlo.py tests/test_universal_math_engine.py tests/test_shockwave_catalog_endpoint.py)
EXISTING=(); for t in "${TRIP[@]}"; do [ -f "$t" ] && EXISTING+=("$t"); done
if [ ${#EXISTING[@]} -gt 0 ]; then
  if "$PY" -m pytest "${EXISTING[@]}" -q; then ok "tripwires green"; else fail "a tripwire FAILED"; STEP_FAIL=1; fi
else warn "no tripwire test files found (skipping)"; fi

if [ "$FULL" -eq 1 ]; then
  head "Step 2b — full backend suite (--full)"
  if "$PY" -m pytest tests/ -q; then ok "full backend suite green"; else fail "full suite has failures (review; some may be pre-existing/infra)"; STEP_FAIL=1; fi
fi

# ── summary ──
head "Summary"
if [ "$STEP_FAIL" -eq 0 ]; then
  ok "ALL CHECKS PASSED"
  echo "  Next: ${B}git add $GOLDEN && git commit${N} the reviewed baseline,"
  echo "  then enable the per-cohort toggles (Memory → SLO feedback → Promises first) and playtest."
  exit 0
else
  fail "ONE OR MORE STEPS FAILED — see above (start with Step 0 if config constants were missing)"
  exit 1
fi
