import docx
import os
from docx.shared import Pt, Inches
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT

def append_to_document():
    filepath = r"c:\Users\Home\.gemini\antigravity\scratch\muressons-sim\Muressons_Modules_Technical_Guide.docx"
    
    if os.path.exists(filepath):
        doc = docx.Document(filepath)
        doc.add_page_break()
    else:
        doc = docx.Document()
    
    # Title for new section
    title = doc.add_heading('Frontend Integration & Component Mapping', 0)
    title.alignment = WD_PARAGRAPH_ALIGNMENT.CENTER
    
    doc.add_paragraph(
        "To provide a complete end-to-end architectural view, this section outlines how the newly integrated "
        "backend simulation modules map directly to the React frontend components driving the user experience. "
        "These components serve as the interactive layer where players experience the friction, feedback loops, "
        "and systemic consequences calculated by the backend engines."
    )
    
    mappings = [
        {
            "frontend": "BoardroomShowdown.js",
            "backend": "Board Governance (board_governance.py) & Org Politics (org_politics.py)",
            "description": "Serves as the interactive UI for the governance minigame. It pulls the C-suite alignment scores and board composition from the global state. Players use this component to drag-and-drop political capital to sway votes. If the calculated 'Approval_Confidence' is below the threshold, this component triggers the friction UI, forcing players to either negotiate or brute-force the decision at a severe OPEX penalty."
        },
        {
            "frontend": "StrategicPillarsWorkspace.js",
            "backend": "Branching Engine (branching_engine.py) & Meadows Leverage (meadows_leverage.py)",
            "description": "The central hub where players allocate capital and define their macro-strategy. This component feeds decision data directly into the Branching Engine to calculate the 'Exploration_Ratio'. Additionally, the UI uses color-coding to reflect the 'Intervention Impact Score' from the Meadows Leverage framework, subtly hinting to players whether their strategies are surface-level (Level 12) or paradigm-shifting (Level 3)."
        },
        {
            "frontend": "UniversalBroadcast.js",
            "backend": "NPC Stakeholders (npc_stakeholders.py) & Dynamic Cases (dynamic_cases.py)",
            "description": "The primary notification delivery system for the simulation. When the NPC Stakeholders engine calculates a Salience score > 8, it fires an event to UniversalBroadcast.js, which renders the LLM-generated activist demands or regulatory fines. It also displays the contextually injected real-world case studies generated by dynamic_cases.py when players encounter specific crises."
        },
        {
            "frontend": "StochasticDiceRoll.js",
            "backend": "Market Dynamics (market_dynamics.py) & TCFD Scenarios (tcfd_scenarios.py)",
            "description": "Provides visual suspense for non-deterministic events. When calculating physical climate damage (TCFD) or resolving information asymmetry penalties in multiplayer markets (Market Dynamics), this component renders a probabilistic 'roll' based on the risk exposure factors. It visually communicates that while the mathematical expected value is known, the exact impact contains systemic variance."
        },
        {
            "frontend": "ArchetypeEditor.js & ExecutiveCockpit.module.css",
            "backend": "Balance Sheet Engine (balance_sheet.py) & Biodiversity Engine (biodiversity_engine.py)",
            "description": "The Executive Cockpit styling provides the structured dashboard view, while the underlying data hooks bind to the Balance Sheet Engine (displaying Stranded Assets and Adjusted Equity) and the Biodiversity Engine (displaying the Ecosystem Health Index). The Archetype Editor allows facilitators to manually tweak the starting conditions for these engines, creating custom scenarios."
        }
    ]

    for mapping in mappings:
        doc.add_heading(f"Component: {mapping['frontend']}", level=1)
        
        doc.add_heading('Backend Engine Link', level=2)
        doc.add_paragraph(mapping["backend"])
        
        doc.add_heading('UI/UX Operationalisation', level=2)
        doc.add_paragraph(mapping["description"])

    new_filepath = r"c:\Users\Home\.gemini\antigravity\scratch\muressons-sim\Muressons_Modules_Full_Stack_Guide.docx"
    doc.save(new_filepath)
    print(f"Document successfully appended and saved to {new_filepath}")

if __name__ == '__main__':
    append_to_document()
