'use client';

/**
 * Glossary — Centralized abbreviation definitions + `<Abbr>` component.
 *
 * Usage:
 *   import { Abbr, GLOSSARY } from './Glossary';
 *   <Abbr term="ESG" />            → renders <abbr title="...">ESG</abbr>
 *   <Abbr term="NCD">NCD Risk</Abbr> → renders <abbr title="...">NCD Risk</abbr>
 */

export const GLOSSARY = {
    // Core simulation terms
    ESG: 'Environmental, Social, and Governance',
    BU: 'Business Unit',
    OPEX: 'Operating Expenditure — ongoing costs to run a business unit',
    CAPEX: 'Capital Expenditure — one-time investment spending',
    NCD: 'Natural Capital Debt — accumulated environmental damage',
    SL: 'Social License — community and stakeholder trust score (0–100)',
    CSF: 'Corporate Strategic Fund — pooled investment budget from treasury',

    // Valuation terms
    EBITDA: 'Earnings Before Interest, Taxes, Depreciation, and Amortisation',
    TV: 'Terminal Value — projected end-game valuation of the corporation',
    MR: 'Regenerative Multiple — bonus/penalty multiplier based on ESG performance',

    // Other
    Rev: 'Revenue — total income generated by a business unit',
    Rep: 'Reputation — public perception score affecting talent and partnerships',
    GHG: 'Greenhouse Gas — emissions contributing to climate change',
    'M\u2098': 'Regenerative Multiple',
    'V\u209C': 'Terminal Value',
};

/**
 * <Abbr> component — wraps text in a styled <abbr> with tooltip.
 *
 * Props:
 *  - term: key from GLOSSARY (e.g. "ESG", "NCD")
 *  - children: optional custom display text (defaults to term)
 */
export function Abbr({ term, children }) {
    const definition = GLOSSARY[term];
    return (
        <abbr
            title={definition || term}
            style={{
                textDecoration: 'underline dotted',
                textDecorationColor: 'rgba(99, 102, 241, 0.4)',
                textUnderlineOffset: '3px',
                cursor: 'help',
            }}
        >
            {children || term}
        </abbr>
    );
}

export default Abbr;
