'use client';

/**
 * Glossary — Centralized abbreviation definitions + `<Abbr>` component.
 *
 * Usage:
 *   import { Abbr, GLOSSARY } from './Glossary';
 *   <Abbr term="ESG" />            → renders <abbr title="...">ESG</abbr>
 *   <Abbr term="NCD">NCD Risk</Abbr> → renders <abbr title="...">NCD Risk</abbr>
 */

export const GLOSSARY = {
    // ── Financial Metrics ──────────────────────────────────────────
    ESG: 'Environmental, Social, and Governance — three pillars for measuring corporate sustainability',
    BU: 'Business Unit — one of four Muressons divisions (Pharma, Electronics, Consumer Goods, Software)',
    OPEX: 'Operating Expenditure — ongoing costs to run a business unit, reduced by the Synergy Engine',
    CAPEX: 'Capital Expenditure — one-time investment per BU from the CSF pool',
    CSF: 'Corporate Strategic Fund — total liquidity pool: Σ(Revenue - OPEX) - Dividends',
    EBITDA: 'Earnings Before Interest, Taxes, Depreciation, and Amortisation — primary profitability metric',
    TV: 'Terminal Value — end-game valuation: EBITDA × Exit Multiple (12×) × Regenerative Multiple (M_R)',
    GTF: 'Green Transition Fund — ring-fenced capital for sustainable transition costs (R7-R9)',
    CoC: 'Cost of Capital — investor-required rate of return, follows macro interest rate cycles',

    // ── Sustainability Metrics ─────────────────────────────────────
    NCD: 'Natural Capital Debt — accumulated environmental damage, compounds each round via interest',
    SLO: 'Social License to Operate — community and worker trust score (0–100). Below 75 triggers Instability Discount',
    SL: 'Social License — community and stakeholder trust score (0–100)',
    CI: 'Carbon Intensity — CO₂ emissions per $M revenue, taxed at R10 ($250/tonne)',
    GHG: 'Greenhouse Gas — emissions contributing to climate change (Scope 1, 2, 3)',
    Rep: 'Group Reputation — stakeholder perception score (0–100). Below 65 triggers Brain-Drain',
    Rev: 'Revenue — total income generated by a business unit',
    WRI: 'Workforce Readiness Index — global competence score affecting pillar effectiveness',

    // ── Scoring & Valuation ────────────────────────────────────────
    MR: 'Regenerative Multiple (M_R) — sustainability-adjusted valuation modifier (range 0.60–2.08)',
    'M\u2098': 'Regenerative Multiple — risk-adjusted valuation modifier based on ESG performance',
    'V\u209C': 'Terminal Value — projected end-game valuation of the corporation',

    // ── Frameworks & Regulation ────────────────────────────────────
    CSRD: 'Corporate Sustainability Reporting Directive — EU regulation mandating double materiality assessments',
    TCFD: 'Task Force on Climate-related Financial Disclosures — framework for disclosing climate risks',
    SBTi: 'Science Based Targets initiative — emissions reduction aligned with Paris Agreement',
    VRIO: 'Value, Rarity, Inimitability, Organisation — strategic resource analysis (Barney, 1991)',
    DM: 'Double Materiality — assessing both financial risk TO and societal impact FROM the company',

    // ── Engine Abbreviations ───────────────────────────────────────
    FX: 'Foreign Exchange — stochastic currency movements affecting BU revenue (±5%)',
    DSO: 'Days Sales Outstanding — working capital measure affected by governance risk',
    NPC: 'Non-Player Competitor — NPC competitor growing at 6%/round in competitive index',
    IFRS: 'International Financial Reporting Standards — accounting framework for financial statements',
    GCoD: 'Green Cost of Debt — annualised financial burden from ecological liabilities',
    TBL: 'Triple Bottom Line — People, Planet, Profit framework for balanced reporting',
    BSC: 'Balanced Scorecard — strategic planning framework linking KPIs to strategy',
};

/**
 * <Abbr> component — wraps text in a styled <abbr> with tooltip.
 *
 * Props:
 *  - term: key from GLOSSARY (e.g. "ESG", "NCD")
 *  - children: optional custom display text (defaults to term)
 */
export function Abbr({ term, children }) {
    const definition = GLOSSARY[term];
    return (
        <abbr
            title={definition || term}
            style={{
                textDecoration: 'underline dotted',
                textDecorationColor: 'rgba(99, 102, 241, 0.4)',
                textUnderlineOffset: '3px',
                cursor: 'help',
            }}
        >
            {children || term}
        </abbr>
    );
}

export default Abbr;
