#!/usr/bin/env python3
"""Balance report — measure whether each lever moves outcomes (roadmap W4.1).

C-1 survived thirty cohorts because nobody measured whether each option
actually moved outcomes. This script plays scripted strategies through the
REAL engine pipeline (dry_run.py: pre_tick → process_tick → post_tick →
run_new_engines, the same call chain as commit-turn), deterministically
(fixed seeds + cohort stochastic_seed streams), and reports:

  1. strategy outcomes — terminal value / M_R / archetype / final treasury
     for pure strategies (all-A/B/C), the four facilitator bots, per paradigm;
  2. M_R component attainment — which breakdown components any run earned
     (a component no strategy can reach is either minigame/side-track gated —
     note it — or dead);
  3. lever sensitivity — for each round, the terminal-value delta of switching
     that ONE round away from the all-B baseline: a ~zero row is a dead lever.

Usage:
    python3 scripts/balance_report.py            # print report
    python3 scripts/balance_report.py --write    # write BALANCE_REPORT_BASELINE.md

Run each release, regenerate, and read the diff: a collapsed spread, a lost
component, or a newly-dead lever is a balance regression the unit suite
cannot see.
"""

import copy
import os
import sys
from collections import Counter

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_BACKEND = os.path.join(_ROOT, "backend")
sys.path.insert(0, _BACKEND)
sys.path.insert(0, os.path.join(_BACKEND, "tests"))
os.environ.setdefault("USE_MEMORY_DB", "true")

import dry_run  # noqa: E402
import test_universal_math_engine as UME  # noqa: E402

_SEED = 424242  # one fixed seed: the report is a baseline, not a distribution

PURE = {
    "pure_A": {r: "option_a" for r in range(1, 11)},
    "pure_B": {r: "option_b" for r in range(1, 11)},
    "pure_C": {r: "option_c" for r in range(1, 11)},
}
BOTS = ["aggressive_green", "extractive", "balanced"]  # chaotic excluded: rng-driven
# legacy only: pillar (multi_toggles) impact application lives in the ROUTER
# (single-applier design, fix/pillar-impact-ownership), which this headless
# harness bypasses — a pillar-mode balance report needs the router path and
# is future work, noted in the PLAN.
PARADIGM = "legacy_abc"
COMPOSITION = "DEFAULT_4_BU"
# C-2 (owner calibration ruling, 2026-09-05): the reference strategies deploy
# REFERENCE_CAPEX_FRAC of the CSF pool per round — the median substantive
# allocation in the 241 stored real BU rows (0.20-1.00, median 0.50), not the
# 10 % that made every reference row a serial greenwasher and, after SOC-4,
# bankrupt by R6. The ladder keeps its low rungs on purpose: 5 % and 10 % are
# under the greenwash bars (C-1: the team's share of the pool, 15 % full /
# ≈10 % moderate) and show what that costs.
REFERENCE_CAPEX_FRAC = 0.50
CAPEX_LADDER = [0.05, 0.10, 0.20, 0.35, 0.60]


def _register(name: str, choice_map: dict, capex_frac: float = REFERENCE_CAPEX_FRAC) -> str:
    dry_run._EXTRA_STRATEGIES[name] = {
        "label": name, "capex_frac": capex_frac, "dividends": 0,
        "scorer": "balanced", "choice_map": choice_map,
    }
    return name


def _initial_state():
    bus = UME.BU_COMPOSITION_FACTORIES[COMPOSITION]()
    gs = UME.make_global_state(paradigm="legacy_abc")
    return gs, bus


def run_strategy(name: str, paradigm: str) -> dict:
    gs, bus = _initial_state()
    out = dry_run._run_one(copy.deepcopy(gs), copy.deepcopy(bus), name,
                           seed=_SEED, end_round=10, paradigm=paradigm,
                           ped_overrides={}, difficulty_tier="standard")
    t = out.get("terminal") or {}
    return {
        "tv": t.get("terminal_value", 0.0),
        "mr": t.get("regenerative_multiple", 0.0),
        "archetype": t.get("archetype", "?") or "?",
        "treasury": out.get("final_treasury"),
        "bankrupt_round": out.get("bankrupt_round"),
        "breakdown": t.get("mr_breakdown", {}),
    }


def _m(v):
    return f"{(v or 0)/1e6:,.1f}M"


def build_report() -> str:
    for name, cmap in PURE.items():
        _register(name, cmap)

    lines = []
    lines.append("# Balance Report Baseline")
    lines.append("")
    lines.append("Generated by `scripts/balance_report.py` — do not edit by hand.")
    lines.append("Regenerate with `python3 scripts/balance_report.py --write` and commit the")
    lines.append("diff with any behavioural release. All runs use the production call chain")
    lines.append("(dry_run.py) with fixed seeds, so this file changes only when behaviour does.")
    lines.append("Bots do not play the R2 materiality minigame or side tracks; components")
    lines.append("gated behind those are expected to show 0% attainment here.")
    lines.append("")
    lines.append("Baseline history (why the reference numbers moved):")
    lines.append("- 2026-09-05 (audit remediation Wave 2, WP-21 regeneration): the bot ladder")
    lines.append("  invests at ratios 0.0125–0.15 with green claims, below the 15 % / ≈10 %")
    lines.append("  greenwash bars, so it greenwashes in most rounds. Two audit findings make")
    lines.append("  that cost what the model says it costs: SOC-4 (a greenwashing scandal is a")
    lines.append("  betrayal for NPC/agent trust memory → escalation, enforcement, cascades)")
    lines.append("  and FLAG-9 (`greenwashing_detected` now written → +15 pp whistleblower /")
    lines.append("  +12 pp SEC-rule black-swan odds). pure_B went from $482M / $141M treasury")
    lines.append("  (after WP-23) to $124M / −$87M, bankrupt R6; reverting those two alone")
    lines.append("  restores $482M / $139M. Real teams (241 stored decisions) invest at")
    lines.append("  0.20–1.00, median 0.50, and rarely trip the bars — the ladder is a serial")
    lines.append("  greenwasher by construction; a ladder at realistic ratios is the owner's")
    lines.append("  call. WP-21 itself (natural decay on each BU's own ratio) moves nothing")
    lines.append("  here: every bot gives all four BUs the same ratio.")
    lines.append("- 2026-09-05 (owner calibration rulings C-1 / C-2): C-1 — the greenwash bar")
    lines.append("  is the TEAM'S share of the CSF pool (sum of the BU ratios), not their")
    lines.append("  average, which had made 15 % mean 60 % of the pool for a four-BU group;")
    lines.append("  the archetypal real team (one BU at ~50 % of the pool, $1 elsewhere) is")
    lines.append("  no longer a greenwasher. C-2 — the reference strategies deploy 50 % of")
    lines.append("  the pool (the real median substantive allocation) instead of 10 %; the")
    lines.append("  ladder keeps its 5 % / 10 % rungs to show the greenwash cliff. Every")
    lines.append("  reference row therefore moved; the low rungs are the only rows that still")
    lines.append("  greenwash, and they are meant to.")
    lines.append("")

    # ── 1. strategy outcomes ──
    lines.append(f"## 1. Strategy outcomes ({COMPOSITION}, {PARADIGM}; capex {REFERENCE_CAPEX_FRAC:.0%} of CSF pool unless noted)")
    lines.append("")
    lines.append("| Strategy | Terminal Value | M_R | Archetype | Final treasury | Bankrupt |")
    lines.append("|---|---|---|---|---|---|")
    all_runs = []
    for name in list(PURE) + BOTS:
        r = run_strategy(name, PARADIGM)
        all_runs.append(r)
        lines.append(f"| {name} | ${_m(r['tv'])} | {r['mr']:.2f} | "
                     f"{r['archetype']} | ${_m(r['treasury'])} | "
                     f"{'R' + str(r['bankrupt_round']) if r['bankrupt_round'] else '—'} |")
    lines.append("")
    tvs = [r["tv"] for r in all_runs]
    lo, hi = min(tvs), max(tvs)
    spread = f"{hi/lo:.1f}x" if lo > 0 else "unbounded (a strategy ends below TV $0)"
    lines.append(f"Spread: ${_m(lo)} … ${_m(hi)}  ({spread})")
    lines.append("")

    # ── 1b. the capex ladder: the game's biggest lever, measured ──
    lines.append("### 1b. CapEx intensity ladder (pure_B choices, varying capex share of CSF pool)")
    lines.append("")
    lines.append("| CapEx share | Terminal Value | M_R | Final treasury | Bankrupt |")
    lines.append("|---|---|---|---|---|")
    for frac in CAPEX_LADDER:
        name = _register(f"ladder_B_{int(frac*100)}", dict(PURE["pure_B"]), capex_frac=frac)
        r = run_strategy(name, PARADIGM)
        all_runs.append(r)
        lines.append(f"| {frac:.0%} | ${_m(r['tv'])} | {r['mr']:.2f} | ${_m(r['treasury'])} | "
                     f"{'R' + str(r['bankrupt_round']) if r['bankrupt_round'] else '—'} |")
    lines.append("")

    # ── 2. M_R component attainment ──
    lines.append("## 2. M_R component attainment (across all runs above)")
    lines.append("")
    # The documented calculate_mr component set; 0% rows are the signal.
    KNOWN_COMPONENTS = [
        "materiality_governance", "synergy_bonus", "resilience_bonus",
        "truth_premium", "community_champion_bonus", "just_transition_bonus",
        "workforce_bonus", "wellbeing_bonus", "instability_discount",
    ]
    counts = Counter()
    for r in all_runs:
        for k, v in r["breakdown"].items():
            if k not in ("base",) and not k.startswith("max_") and v:
                counts[k] += 1
    lines.append("| Component | Runs earning it | Share |")
    lines.append("|---|---|---|")
    seen = set()
    for k, n in sorted(counts.items(), key=lambda kv: (-kv[1], kv[0])):
        seen.add(k)
        lines.append(f"| {k} | {n}/{len(all_runs)} | {n/len(all_runs):.0%} |")
    for k in KNOWN_COMPONENTS:
        if k not in seen:
            lines.append(f"| {k} | 0/{len(all_runs)} | **0% — unreachable for these strategies** |")
    lines.append("")
    lines.append("Expected 0% here: `materiality_governance` (R2 minigame accuracy, which")
    lines.append("bots do not play), `synergy_bonus`/`truth_premium`/`workforce_bonus`")
    lines.append("(require specific choice+investment paths). A component at 0% that a")
    lines.append("REAL cohort also never earns is a calibration finding — cross-check with")
    lines.append("the cohort telemetry report (W4.3).")
    lines.append("")

    # ── 3. lever sensitivity ──
    base = run_strategy("pure_B", PARADIGM)
    lines.append(f"## 3. Lever sensitivity ({PARADIGM}, baseline pure_B @ {REFERENCE_CAPEX_FRAC:.0%} capex: "
                 f"TV ${_m(base['tv'])}, M_R {base['mr']:.2f})")
    lines.append("")
    lines.append("Switching ONE round away from all-B. A ~zero row is a dead lever for")
    lines.append("this trajectory (C-1's failure mode, measured).")
    lines.append("")
    lines.append("| Round | → option | Δ Terminal Value | Δ M_R | Δ final treasury |")
    lines.append("|---|---|---|---|---|")
    dead = []
    for rnd in range(1, 11):
        row_max = 0.0
        for opt in ("option_a", "option_c"):
            cmap = dict(PURE["pure_B"]); cmap[rnd] = opt
            name = _register(f"sweep_r{rnd}_{opt[-1]}", cmap)
            r = run_strategy(name, PARADIGM)
            dtv = r["tv"] - base["tv"]; dmr = r["mr"] - base["mr"]
            dtr = (r["treasury"] or 0) - (base["treasury"] or 0)
            row_max = max(row_max, abs(dtv))
            lines.append(f"| R{rnd} | {opt[-1].upper()} | {'+' if dtv >= 0 else '−'}${_m(abs(dtv))} | "
                         f"{dmr:+.2f} | {'+' if dtr >= 0 else '−'}${_m(abs(dtr))} |")
        if base["tv"] and row_max < 0.005 * abs(base["tv"]):
            dead.append(rnd)
    lines.append("")
    if dead:
        lines.append(f"**Dead levers (|ΔTV| < 0.5% of baseline for every option): "
                     f"{', '.join('R' + str(x) for x in dead)}** — investigate.")
    else:
        lines.append("**No dead levers: every round's options move terminal value by ≥0.5%.**")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    report = build_report()
    if "--write" in sys.argv:
        out = os.path.join(_ROOT, "BALANCE_REPORT_BASELINE.md")
        with open(out, "w", encoding="utf-8", newline="") as f:
            f.write(report + "\n")
        print(f"wrote {out}")
    else:
        print(report)
