export const DETAILED_DESCRIPTIONS = {
  "narrative": {
    "1": {
      "option_a": "Mandate a rapid, compliance-only ESG sweep. Fast and cheap, it allows the factories to keep humming without interruption, boosting immediate revenue at the cost of leaving massive, hidden risk pockets in the Electronics layer.",
      "option_b": "Commission a grueling, invasive, layer-by-layer forensic audit across all global business units. It shocks the operations and costs millions upfront but serves as an impregnable shield against impending supply chain exposures.",
      "option_c": "Compromise by auditing the high-visibility BUs (Pharma, Consumer) while quietly deferring the murky Electronics division. A middle path that saves some cash but critically fails to secure the most vulnerable flank from future crises."
    },
    "2": {
      "option_a": "Strictly filter all capital expenditures through the Double Materiality lens. Divest immediately from high-return but toxic ESG assets, sacrificing short-term revenue to slash structural governance risk permanently.",
      "option_b": "Formally adopt the Materiality framework but lobby the board to grant \"strategic exceptions\" to keep highly profitable, dirty legacy operations running a bit longer. Checks the box while stalling the pain.",
      "option_c": "Reject the CFO\u2019s framework entirely. Greenlight lucrative, high-carbon expansion projects to aggressively pump short-term earnings, severely antagonizing regulators and exposing the firm to future compliance slaughter."
    },
    "3": {
      "option_a": "Terminate legacy mega-suppliers and forcefully migrate 100% of sourcing to low-carbon vendors overnight. Instantly slashes carbon but triggers violent supply shock, missing quotas and plummeting revenue.",
      "option_b": "Issue structured financial instruments to directly subsidize your legacy suppliers\u2019 carbon transitions. Keeps the supply lines flowing flawlessly while strategically sinking your overarching Natural Capital Debt.",
      "option_c": "Purchase cheap, low-tier carbon offsets to artificially balance the ledger on paper. Push the real physical supply chain restructuring down the roadmap, hoping the regulatory hammer falls on a successor CEO."
    },
    "4": {
      "option_a": "Open the gates. Voluntarily invite human rights NGOs and hostile journalists to tear through the Electronics supply chain, absorbing a brutal initial financial hit to definitively rip out the systemic rot.",
      "option_b": "Retain elite, aggressive crisis communications firms to flood search engines, stall reporters, and tightly manage the viral fallout. Contains the bleeding slightly but leaves the root operational rot entirely untreated.",
      "option_c": "Direct the Corporate Counsel to issue combative, zero-liability denials. Attempt to aggressively out-litigate the controversy for free. If the Electronics Blindspot exists, this choice detonates the company's valuation."
    },
    "5": {
      "option_a": "Deploy massive capital to pour concrete and build brutalist flood walls around the primary manufacturing corridor before the cyclone hits. Secures revenue mechanically but destroys the surrounding coastal ecology.",
      "option_b": "Fund the rapid restoration of massive wetland and mangrove acreage to act as a porous, absorbing sponge against the Category 4 storm surge. A gentler, slower, but ecologically profound barrier.",
      "option_c": "Abandon physical defenses entirely. Simply purchase astronomical premiums on parametric weather insurance, accepting that the factories will flood but betting the financial payout will cover the structural losses."
    },
    "6": {
      "option_a": "Ignore the ethical outcry entirely. Package the highly aggressive, discriminatory profiling algorithm into a bespoke B2B product and sell it to external mega-corps for immense, immediate licensing windfalls.",
      "option_b": "Halt the highly profitable Software division entirely. Institute a draconian ethics board review, scrub the biased models, and undergo an agonizing operational pivot aimed at restoring ultimate stakeholder trust.",
      "option_c": "Deploy engineers in the dead of night to secretly write a filter blocking the biased output from reaching the UI. No apology, no recall. A massive ticking time bomb if whistleblowers ever reverse-engineer the logs."
    },
    "7": {
      "option_a": "Completely overhaul legacy product architectures. R&D must design 100% of upcoming SKUs for modular disassembly and total material recycling to decisively crush the looming EU compliance threat.",
      "option_b": "Dodge the core redesign but heavily fund expansive global take-back recycling programs to intercept old product before it reaches landfills. A moderate, logistics-heavy half-measure.",
      "option_c": "Partner with heavy industry to build sprawling incinerators. Turn the millions of tons of waste generated by the Consumer Goods BU into burnable fuel to power the other divisions, unlocking extreme operational synergy."
    },
    "8": {
      "option_a": "Mandate grueling, across-the-board water rationing across the entire corporate footprint. Every BU suffers, but the shared sacrifice prevents targeted union outrage and preserves baseline social license.",
      "option_b": "Cut off the water mains to Pharma and Consumer Goods completely to protect the ultra-high-margin Electronics manufacturing lines. Instantly provokes vicious, localized labor riots in the sacrificed divisions.",
      "option_c": "Disregard the failing municipal grid entirely. Authorize $30 million in pure CapEx to construct a sprawling corporate desalination plant complex, achieving near-absolute insulation from future ecological volatility."
    },
    "9": {
      "option_a": "Lock the carbon-heavy factory gates at midnight. Maximize immediate balance sheet savings by liquidating the workforce instantly. If Social License is already low, this guarantees a crippling, 100% revenue-halting global strike.",
      "option_b": "Subsidize the polluting factories artificially for 24 months. Bleed capital to orchestrate an impossibly smooth, intensely managed phase-out that retrains workers and preserves the corporate brand unconditionally.",
      "option_c": "Establish an astonishing $20 million sovereign-wealth style community defense fund to rebuild the devastated manufacturing towns, acting as the ultimate, unbreachable armor against any union strike actions."
    },
    "10": {
      "option_a": "Look the activist billionaire in the eye and refuse to split the company. Requires proof of a deeply integrated, massively successful Corporate Synergy engine (>80 score) constructed over the past decade to survive the board vote.",
      "option_b": "Throw a bone to the activists. Identify the lowest-margin Business Unit dragging down the balance sheet and spin it off to artificially compress and juice the remaining EBITDA multiple.",
      "option_c": "Unconditional surrender. Slice the global conglomerate into independent pieces and sell them to private equity to extract the absolute maximum immediate cash out value, permanently destroying the long-term Synergy Multiple."
    }
  },
  "pillars": {
    "1": {
      "energy": {
        "option_1": "Lock in a 10-year Power Purchase Agreement (PPA) to shift corporate energy consumption to off-site renewable sources. This provides a stable, long-term carbon reduction without the massive upfront capital of physical infrastructure.",
        "option_2": "Take no action and maintain the existing dependence on fossil fuels. This saves cash initially but immediately flags the company as a laggard, driving early carbon intensity penalties.",
        "option_3": "Commit heavy capital to physically build on-site solar arrays across critical manufacturing facilities. Provides massive, permanent structural carbon reduction and independence from external grid pricing."
      },
      "operations": {
        "option_1": "Mandate lean manufacturing principles group-wide to eliminate waste and optimize material throughput. A low-cost, steady approach to baseline improvement.",
        "option_2": "Invest in advanced digital twin technology to create virtual models of factories. Enables predictive maintenance and operational foresight, reducing future governance or breakdown risks.",
        "option_3": "Proceed with \"business as usual\" operations. Saves immediate budget but leaves the organization vulnerable to stagnation penalties."
      },
      "supply_chain": {
        "option_1": "Commission aggressive, deep-tier (1 through 3) ESG forensic audits across the entire global supplier base. This exposes hidden risks early, insulating the brand from future Contagion shocks.",
        "option_2": "Screen only direct (Tier-1) suppliers. This surface-level approach saves money but leaves critical blind spots deeper in the value chain, specifically in Electronics.",
        "option_3": "Completely postpone supply chain assessments to preserve cash flow. Guarantees that hidden supply chain violations will eventually detonate into brand crises."
      },
      "offsetting": {
        "option_1": "Directly fund verified nature-based solutions like reforestation and mangrove restoration. Operates outside the core business to reliably pay down legacy Natural Capital Debt.",
        "option_2": "Purchase standard verified carbon credits on the open market. A fast, transactional way to offset footprint, though it generates less brand capital than bespoke nature projects.",
        "option_3": "Make zero external mitigations. Natural Capital Debt will accrue rapidly, driving up the cost of capital for future borrowing across the entire simulation."
      }
    },
    "2": {
      "energy": {
        "option_1": "Execute a fast, administrative switch transferring all corporate utility plans to certified green tariffs. Quick execution but lacks long-term structural resilience compared to physical upgrades.",
        "option_2": "Retrofit existing buildings and factories with smart HVAC routing and advanced LED industrial lighting to permanently lower baseline energy consumption.",
        "option_3": "Avoid transitioning facility contracts. Saves compliance capital but concedes ground on crucial decarbonization goals."
      },
      "operations": {
        "option_1": "Form a highly visible, external-facing materiality oversight committee. This deeply integrates ESG into core governance, drastically lowering the risk of regulatory backlash and union unrest.",
        "option_2": "Check the boxes. Assign materiality compliance to existing legal teams to meet regulatory minimums without transforming the corporate culture.",
        "option_3": "Deliberately ignore the Double Materiality framework. Treat ESG as a pure marketing exercise while chasing short-term profit, inviting brutal governance backlash."
      },
      "supply_chain": {
        "option_1": "Deploy distributed ledger technology to record and verify every supply chain handoff permanently. Offers maximum transparency but requires immense upfront tech capital.",
        "option_2": "Commission a comprehensive, glossy ESG supply chain report. It shapes external narrative and appeases basic investor queries, but lacks the raw proof of blockchain tracking.",
        "option_3": "Keep supplier identities and practices fiercely guarded as proprietary secrets. Degrades trust across external stakeholder networks."
      },
      "offsetting": {
        "option_1": "Endow a massive $3M multi-region impact fund designed to inject capital directly into the communities surrounding corporate operations. The ultimate buffer against local union strikes.",
        "option_2": "Implement internal, comprehensive health, wellness, and continuous development programs for the existing workforce. Solidifies internal morale.",
        "option_3": "Ignore secondary stakeholder welfare. Preserves cash flow but leaves labor morale highly brittle ahead of future workforce frictions."
      }
    },
    "3": {
      "energy": {
        "option_1": "Mandate the immediate retirement of internal combustion logistics and convert 100% of the distribution fleet to electric vehicles. Highly disruptive and extremely expensive.",
        "option_2": "Phase in hybrid trucks and ships over a multi-year period. A practical, compromised approach to fleet modernization without shocking the balance sheet.",
        "option_3": "Keep the legacy diesel fleet running to extract maximum lifespan. Pushes the massive Scope 3 carbon problem down the road."
      },
      "operations": {
        "option_1": "Redesign the entire manufacturing line topology to recapture, recycle, and re-input waste materials on-site. Extremely complex integration but structurally eliminates natural capital debt generation.",
        "option_2": "Set aggressive 50% waste reduction KPIs. Relies on behavioral and policy shifts rather than heavy mechanical re-engineering.",
        "option_3": "Keep linear take-make-dispose manufacturing active to maximize current high-speed material throughput."
      },
      "supply_chain": {
        "option_1": "Terminate contracts with carbon-heavy suppliers immediately and pivot to unproven, low-carbon vendors. Forces compliance but risks massive delays and breaks localized relationships.",
        "option_2": "Structure and issue specialized Green Bonds precisely aimed at financially subsidizing your existing suppliers to upgrade their own carbon-heavy equipment.",
        "option_3": "Purchase temporary carbon offsets to artificially \"net\" the footprint while waiting for regulations to become legally binding before acting."
      },
      "offsetting": {
        "option_1": "Legally commit the firm to Science-Based Targets initiative (SBTi) 1.5\u00b0C pathways. Locks the firm into grueling accountability but elevates the brand to Tier-1 status globally.",
        "option_2": "Buy standard voluntary offsets to mitigate the worst of the Scope 3 disclosures without taking on the restrictive covenants of SBTi targeting.",
        "option_3": "Run a high-gloss PR campaign pledging \"Net Zero Eventually\" with zero immediate operational restructuring or binding verification. Classic greenwashing risk."
      }
    },
    "4": {
      "energy": {
        "option_1": "Aggressively accelerate the timeline for 100% renewable power as a \"good faith\" distraction and pivot narrative away from the Electronics supply chain disaster.",
        "option_2": "Keep energy commitments stable. Do not use environmental spending as a shield for a social/labor crisis.",
        "option_3": "Ruthlessly harvest the energy transition budget to build an emergency war chest for impending crisis litigation. Worsens the brand crash."
      },
      "operations": {
        "option_1": "Unlock the doors. Invite hostile media, independent labor auditors, and NGOs directly into the facilities to demonstrate raw transparency and commitment to reform.",
        "option_2": "Deploy global crisis PR agencies to obfuscate the news cycle, flood search engines, and minimize executive exposure to questioning.",
        "option_3": "Execute a combative legal denial. Threaten journalists with defamation and refuse all culpability. The cheapest upfront option, but invites catastrophic, uncontrollable viral spread."
      },
      "supply_chain": {
        "option_1": "Tear down the upstream network. Audit every node, rewrite contracts, and execute sweeping labor reparations across the exposed Electronics supply chain.",
        "option_2": "Perform surgical, isolated terminations of the specific supplier and subcontractor named in the viral expos\u00e9. A targeted scapegoat strategy.",
        "option_3": "Refuse to acknowledge the supply chain breach operationally, insisting it is entirely a public relations issue."
      },
      "offsetting": {
        "option_1": "Immediately establish a massive trust fund dedicated to directly compensating the families and communities affected by the supplier labor violations.",
        "option_2": "Sign a multi-year partnership with an international labor rights NGO to establish independent monitoring programs going forward.",
        "option_3": "Offer no financial compensation or structural olive branches to the affected communities. Allows anger and resentment to fester."
      }
    },
    "5": {
      "energy": {
        "option_1": "Install localized, decentralized microgrids paired with heavy battery storage at all central nodes. Ensures manufacturing survives grid collapse when the storm makes landfall.",
        "option_2": "Rapidly import and install banks of heavy diesel generators. An ugly, carbon-heavy, but thoroughly proven brute-force method to keep power flowing during the crisis.",
        "option_3": "Roll the dice. Assume regional power grids will survive the Category 4 cyclone and hold back cash."
      },
      "operations": {
        "option_1": "Call the civil engineers. Pour millions of tons of concrete to construct massive coastal flood walls and physical barriers around vital coastal infrastructure.",
        "option_2": "Restore hundreds of acres of natural mangroves and wetlands to act as a porous, absorbing buffer against the incoming storm surge. Slower but ecologically profound.",
        "option_3": "Abandon physical defenses. Pay maximum premium spikes for an ironclad parametric insurance policy to guarantee a financial payout after the disaster strikes."
      },
      "supply_chain": {
        "option_1": "Rapidly onboard duplicate suppliers in entirely separate geographic hemispheres to guarantee the storm cannot shut down the entire global input flow.",
        "option_2": "Break long oceanic supply lines and frantically nearshore critical component manufacturing closer to the point of assembly, cutting exposure to Pacific storm tracks.",
        "option_3": "Maintain the highly optimized, fragile, single-point-of-failure global supply routing. Hope the storm misses the critical maritime choke points."
      },
      "offsetting": {
        "option_1": "Create a disaster adaptation fund to pay for hardening *community* assets (local roads, hospitals, shelters) rather than strictly corporate ones before the cyclone hits.",
        "option_2": "Buy secondary financial hedges against specific weather triggers (e.g., wind speeds exceeding 150mph) aimed at offsetting revenue disruption.",
        "option_3": "Offer zero regional or secondary financial support ahead of the life-threatening climate event."
      }
    },
    "6": {
      "energy": {
        "option_1": "The biased AI requires massive compute power. Preemptively migrate the entire Software BU architecture into custom-built, 100% renewable-powered server farms.",
        "option_2": "Send engineers in to aggressively strip down server power-usage effectiveness (PUE) rather than abandoning the existing brown-power data centers.",
        "option_3": "Accept the massive, dirty energy footprint of the expanding AI deployment and ignore the data center efficiency."
      },
      "operations": {
        "option_1": "Stop the presses. Appoint an external oversight AI ethics board, scrap the biased algorithms, and painstakingly retrain the LLMs on sanitized data. Incredibly costly in time and money.",
        "option_2": "Deploy engineers over the weekend to quickly hack a filter into the AI to quietly block the discriminatory outputs. Do not announce a recall. Massive risk if leaked.",
        "option_3": "Double down. Package the highly aggressive, biased profiling algorithm into a B2B product and sell it to external logistics and HR firms for massive instant revenue."
      },
      "supply_chain": {
        "option_1": "Instead of hiring, pivot the AI tool internally into supply chain routing and logistics optimization, utilizing ethical machine learning applications instead of human profiling.",
        "option_2": "Restrict the AI to \"suggestion only\" mode, mandating that every AI-generated hiring or operations profile must be manually countersigned by a human compliance officer.",
        "option_3": "Remove human guardrails. Let the biased AI autonomously dictate supply chain flow and HR profiling at lightning speed."
      },
      "offsetting": {
        "option_1": "Fund a multi-million dollar program to bridge the digital divide, providing hardware and coding bootcamps to the exact minority demographics harmed by the biased AI.",
        "option_2": "Endow university scholarships specifically targeting underrepresented demographics to enter the machine learning and AI fields.",
        "option_3": "Reject any restorative social justice funding in the wake of the algorithmic discrimination scandal."
      }
    },
    "7": {
      "energy": {
        "option_1": "Build monumental Waste-to-Energy incinerators. Instead of paying landfill fines, convert the discarded manufacturing byproducts into self-contained operational power.",
        "option_2": "Retrofit Consumer Goods and Pharma factories with complex pneumatic systems to capture operational waste heat and recycle it to warm facilities and boil water.",
        "option_3": "Ignore the EU circular directives entirely, accept the fines, and continue drawing virgin power from the standard grid."
      },
      "operations": {
        "option_1": "Completely overhaul R&D. Redesign every physical product to be modular, entirely disassemblable, and manufactured from 100% recycled inputs. The gold standard of survival.",
        "option_2": "Fund global take-back logistics. Pay external partners to collect, sort, and process your consumer products at the end of their lifecycle.",
        "option_3": "Pay the EU legal minimums for waste collection tariffs. Make no adjustments to the core physical product design."
      },
      "supply_chain": {
        "option_1": "Establish a multi-continent reverse logistics fleet dedicated exclusively to trucking dead products backwards up the supply chain for refurbishment.",
        "option_2": "Assign a cryptographic digital twin (a \"Passport\") to every core component, logging its metal and plastic origins to prove compliance to EU inspectors.",
        "option_3": "Disdain the circular economy movement. Dig it up, make it, sell it, and let it rot in a landfill."
      },
      "offsetting": {
        "option_1": "Commit deep capital to restoring complex terrestrial biodiversity, buying massive tracts of land simply to protect pristine ecosystems surrounding your factories.",
        "option_2": "Force the Consumer Goods supply chain to migrate entirely to regenerative agriculture vendors, rebuilding topsoil and sequestering carbon naturally.",
        "option_3": "Continue viewing the earth purely as an extraction resource without reinvesting in natural capital baselines."
      }
    },
    "8": {
      "energy": {
        "option_1": "Decommission every water-cooled industrial chiller. Perform an exceedingly expensive retrofit replacing them with closed-loop, air-based dry cooling arrays.",
        "option_2": "Install industrial desalinization and chemical scrubbers locally at the factory level line to endlessly recycle the same batch of water.",
        "option_3": "Let the drought rage. Continue to pump millions of gallons of water from the depleting local watershed to cool the server farms and factories."
      },
      "operations": {
        "option_1": "Universally throttle production and deploy strict, egalitarian water-efficiency mandates across *all* business units so no single BU bears the brunt of the rationing.",
        "option_2": "Cut the water lines to the Pharma and Consumer Goods BUs entirely. Route 100% of the remaining rationing to the high-margin Electronics BU to save profits.",
        "option_3": "Do the impossible. Circumvent the local government completely by spending $30M to construct a private, massive ocean desalination plant to guarantee corporate water security forever."
      },
      "supply_chain": {
        "option_1": "Enforce emergency water tracking and usage audits upon every Tier 1 and Tier 2 supplier to locate the worst geographic leaks in the upstream chain.",
        "option_2": "Immediately break contracts with thirsty, legacy suppliers and shift production to vendors utilizing precision, zero-water-waste manufacturing techniques.",
        "option_3": "Ignore upstream water usage. Let the suppliers figure out how to navigate the regional droughts themselves."
      },
      "offsetting": {
        "option_1": "Launch a monumental geo-engineering and ecological effort to physically restore and refill the drained local aquifers and rivers surrounding the communities.",
        "option_2": "Build wells, pipe infrastructure, and purification stations to ensure the impoverished local communities do not lose access to drinking water while the factories keep pumping.",
        "option_3": "Take the remaining water for the corporation and leave the surrounding local communities to dry up."
      }
    },
    "9": {
      "energy": {
        "option_1": "Anticipating the collapse of fossil jobs, build a massive, fully-funded academy bridging the gap to retrain thousands of legacy workers into certified green-energy technicians.",
        "option_2": "Compromise by offering basic retraining subsidies and vouchers to roughly half the affected workforce, leaving the rest to fend for themselves.",
        "option_3": "Distribute basic legal severance packages and walk away. Offer zero structural support for the thousands of suddenly unemployed laborers."
      },
      "operations": {
        "option_1": "Extend the life of the polluting factories artificially by 2 years to orchestrate a meticulously slow, intensely managed phase-out that prevents jarring economic shocks to the union towns.",
        "option_2": "Lock the gates at midnight. Shut down the carbon-heavy factories immediately to instantly slash overhead and optimize the immediate carbon-intensity spreadsheet.",
        "option_3": "Fire the human labor force and replace the obsolete production lines entirely with advanced, carbon-efficient robotic automation. Highly efficient, deeply unpopular."
      },
      "supply_chain": {
        "option_1": "Systematically dismantle reliance on mega-suppliers. Shift contracts to a vast, decentralized web of local, town-level SMEs to inject survival capital directly into the affected region.",
        "option_2": "Facilitate the financial and legal transition of failing legacy suppliers into self-sustaining worker-owned cooperatives.",
        "option_3": "Exploit the transition chaos. Shut down the local supply hubs entirely and migrate all remaining operational sourcing to ultra-cheap, offshore destinations."
      },
      "offsetting": {
        "option_1": "Endow an astonishing $20 million sovereign wealth-style fund specifically dedicated to the economic survival, mental health, and structural pivoting of the doomed manufacturing towns.",
        "option_2": "Use corporate leverage to issue specialized Just Transition municipal bonds, providing the local government with the liquidity required to manage the economic fallout.",
        "option_3": "Let the rust belt rust. Offer zero community bridging or economic support as the corporation abandons the region for greener pastures."
      }
    },
    "10": {
      "energy": {
        "option_1": "Achieve the holy grail. Spend whatever it takes to secure verified, ironclad Net-Zero certification across all scopes, permanently bulletproofing the firm against future systemic carbon taxation.",
        "option_2": "Complete an 80% carbon reduction pathway. It is highly respectable but falls just short of true Net-Zero, leaving a small, permanent taxation vulnerability in the Year 5 ledger.",
        "option_3": "Abandon the pretense. Accept that the BUs will simply run on cheap fossil fuels forever and absorb the massive, permanent Carbon Tax penalties sliced off the top of the terminal valuation."
      },
      "operations": {
        "option_1": "Stare down the activist billionaires. Refuse to break up the company, successfully arguing that the deep, cross-BU Synergy Multiple you spent a decade building justifies keeping the conglomerate intact.",
        "option_2": "Capitulate slightly. Spin off the most sluggish, lowest-margin Business Unit as an independent entity to placate the activists and boost the remaining core EBITDA.",
        "option_3": "Surrender. Shred the conglomerate into entirely distinct pieces, selling them off to private equity for maximum immediate cash. Permanently destroys the 10-year Synergy Multiplier."
      },
      "supply_chain": {
        "option_1": "Achieve terminal evolution. The entire global supply web is now fundamentally regenerative, actively sinking carbon and purifying water baseline ecosystems simply by operating.",
        "option_2": "Lock in a highly diversified, climate-hardened global logistical network that can withstand the extreme weather volatility of the 2040s.",
        "option_3": "Squeeze the final margins. Strip the supply chain down to its bare-metal, cheapest possible iteration, ruthlessly maximizing immediate cash flow for the Year 5 exit multiple."
      },
      "offsetting": {
        "option_1": "Permanently surrender $15 million in capital to found an irrevocable, perpetual sustainability trust that acts as a towering beacon of corporate responsibility for the next century.",
        "option_2": "Re-incorporate the firm structurally. Rewrite the corporate charter to legally bind future boards to a strict stakeholder-first governance covenant.",
        "option_3": "Burn the ESG roadmap. Divert every available dollar of free cash flow in Year 5 exclusively into massive stock buybacks and special dividends. Pure, unadulterated shareholder supremacy."
      }
    }
  }
};
